[package]
name = "monitor-testing"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.50", features = ["derive"] }
core-foundation = "0.9"
core-graphics = "0.23"
flume = "0.11.1"
rdev = "0.5.3"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
